name: Productions Deploy
run-name: Productions Deploy ${{ github.actor }} ${{ github.event_name }} ${{ github.ref }} ${{ github.repository }}

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
      - name: Install
        run: yarn
      - name: Build
        run: yarn dist
      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@5.0.0
        with:
          server: ${{ secrets.PRO_SERVER }}
          username: ${{ secrets.PRO_USERNAME }}
          password: ${{ secrets.PRO_PASSWORD }}
          server-dir: ${{ secrets.PRO_DIR }}
          local-dir: ./htdocs/
          dangerous-clean-slate: true
